### ISSUE TITLE
Downloaded, but won't run

### ISSUE THREAD

**Issue by jaconfurz** [wwyaiykycnf/e621dl#40]
Hello! I'm relatively new at using Python, so there is a possibility i'm doing something wrong. I downloaded your zip, and I have python 2.17 installed. When I run the program through python, it gives this error.
![pythonerror](https://cloud.githubusercontent.com/assets/20798316/25316352/3df5ddee-282b-11e7-80ec-feec2722f87a.JPG)

Maybe im doing something wrong, can someone help? And as a second question, does this program support downloads of gif and videos from the website?

**Comment by DatDraggy** [comment]
Don't use the command line. Just open e621dl.py in python and press F5 to run it. It says that it couldn't find the py file.

**Comment by jaconfurz** [comment]
tried that, i get this error
![pythonerror](https://cloud.githubusercontent.com/assets/20798316/25317312/3a65e168-283c-11e7-8ae5-8404c3fa5123.JPG)

**Comment by Wulfre** [comment]
It looks like the useragent got banned again. The source code includes a useragent that tries to imitate a web browser instead of being honest that its a script.

**Comment by jaconfurz** [comment]
can you send the link to that issue? ill see if i can fix it through that

**Comment by DatDraggy** [comment]
@Wulfre is right. They don't allow imitating of a browser

@jaconfurz here you go https://github.com/wwyaiykycnf/e621dl/issues/39#issuecomment-285446174

**Comment by jaconfurz** [comment]
Thanks, its working now! :D Though one last question. Does this script download existing pictures/videos/sfw? Or does it only download new items as they are posted after the script runs? 

My tag is "Yiff Animation order:score" and its downing 7 posts. Im trying to download like the first 10 pages, sorted by highest rated, is this possible to do?

**Comment by DatDraggy** [comment]
Remove CONFIG['last_run'] = YESTERDAY.strftime(default.DATETIME_FMT) from line 162. Then set the date to something high in the config

**Comment by Wulfre** [comment]
As @DatDraggy mentioned, setting the date to something further back in time will download older posts. Downloading them in order of score won't do much for you though, because the script names the files by their md5, essentially displaying them to you in your directory in a random order.

**Comment by jaconfurz** [comment]
Thank you! :)
