### ISSUE TITLE
Downloader Stopped Working 

### ISSUE THREAD

**Issue by ghost** [wwyaiykycnf/e621dl#42]
Tried multiple versions with no luck.

C:\Users\\Desktop\e621dl-master>py e621dl.py
Traceback (most recent call last):
  File "e621dl.py", line 6, in <module>
    import lib.support as support
  File "C:\Users\\Desktop\e621dl-master\lib\support.py", line 3, in <module>
    import argparse
ImportError: No module named argparse

**Comment by Wulfre** [comment]
Make sure you have the latest version of python 2.7. Argparse didn't exist before 2.7 and the program doesn't work at all in python 3.

**Comment by ghost** [comment]
Installed Python 2.7 
Now I get this error.
C:\Users\Desktop\e621dl-master>py e621dl.py
e621dl      INFO     running e621dl version 2.4.6
Traceback (most recent call last):
  File "e621dl.py", line 45, in <module>
    EARLY_TERMINATE |= not support.validate_config(CONFIG)
  File "C:\Users\Desktop\e621dl-master\lib\support.py", line 141, in validate_config
    assert c['part_used_as_name'] == "id" or \
KeyError: 'part_used_as_name'

**Comment by Wulfre** [comment]
That looks like an error with your config file, but I'm not 100% sure. Do you have a line for the part_used_as_name value in your config?

**Comment by ghost** [comment]
No, it never had it. I don't know why it is just now showing this error.

**Comment by ghost** [comment]
Made a new config file, issue fixed.

**Comment by aleksbrgt** [comment]
Your config file was lacking the property _part_used_as_name_ , introduced a few month ago (#33).
