### ISSUE TITLE
Wrong version displayed, behavior doesn't match readme.md

### ISSUE THREAD

**Issue by AriinPHD** [wwyaiykycnf/e621dl#47]
Version 2.4.6 currently displays version 4.4.1 on Windows.

Also the documentation doesn't seem to fully match the behavior of the program anymore. For example, the program has not created a tags.txt file, only a config.ini file and a default "downloads" folder that cannot be moved/altered.

**Comment by Wulfre** [comment]
It sounds like you are using my fork.

**Comment by AriinPHD** [comment]
Huh! Go figure... You're right @Wulfre! I have been looking for the source for ages. Thanks.

Does that mean that the original e621dl is dead? Last update 2014? I'm giving you a follow to keep up to date on this either way. :)

EDIT: Huh, I *was* following you already... I must have had a major brain fart.

This was an errorous report. Sorry, wwyaiykycnf! Ignore this post! :)
